@startuml

start
:0,道左右両端の座標を取得、保存;
:1,障害物と一番近い走行経路のデータポイント**X**を探索;
:2,ポイント**X-1**と**X**のベクトル、ポイント**X-1**と障害物のベクトルから
障害物が左右どっちにあるかを計算する;
:3,障害物が右にある場合、ポイント**X-7** から **X+5**とそれ
ぞれ一番近い道左端のデータポイント**Y-7**から**Y+5**を探索;
:4,走行経路のデータポイントを道左端に寄せるように更新する
**X -= (X - Y)*重み**;
stop


@enduml